### ISSUE TITLE
[FEAT] Demonstration GIF

### ISSUE THREAD

**Issue by vivifalls** [fathulfahmy/lunarkeymap#3]
A **demonstration GIF** in the `README` showing the keybindings in action in VSCode (preferably with the keypresses showing as well), so users who never actually used Lunarvim can still get a feel for what the keybindings do.

**Comment by fathulfahmy** [comment]
Should it be multiple gifs for each section, workspace navigation, list navigation, etc. or is it better to have just one gif demonstrating everything?

**Comment by vivifalls** [comment]
Better to have multiple gifs so it becomes less tiring to see each functionality multiple times, at least in my opinion.

**Comment by fathulfahmy** [comment]
I have updated the [readme](https://github.com/fathulfahmy/lunarkeymap/blob/main/README.md). Please tell me your opinion on it. Should I add toggle to expand gif or toggle to expand keyboard shortcut per section?

**Comment by fathulfahmy** [comment]
Should I close this issue as completed?

**Comment by vivifalls** [comment]
yeah its pretty good, gonna close this as completed
